filename_prefix: ""

llms:
  llama:
    script: "scripts/api_call_ollama_stories.py"
    model: "llama2"
    strategies: ["synopsis", "flash-fiction", "haiku"]
    output_dir: "./ollama_stories"
    temperatures: [0.7, 1.0, 1.2]
    iterations: 5
