strategies: [none, etymology, random, thesaurus, opposites]
temperatures: [0.7, 1.0, 1.2]
iterations: 5
filename_prefix: "" # this has to be dynamically set from the llms: key in the config.yaml file
llms:
  gpt4:
    script: "scripts/api_call_stories_gpt4.py"
    model: "gpt-4o"
    strategies: ["synopsis", "flash-fiction", "haiku"]
  llama:
    script: "scripts/api_call_dat_ollama.py" # Replace with the actual script name if different
    strategies: [ "etymology","thesaurus"] # Example LLM-specific parameters
