strategies: [none, etymology, random, thesaurus, opposites]
temperatures: [0.7, 1.0, 1.2]
iterations: 5
filename_prefix: "dat_results"
llms:
  gpt4:
    script: "scripts/api_call_dat_gpt4.py"
  stablelm:  # Example for another LLM
    script: "scripts/api_call_dat_stablelm.py"
  gpt-3.5-turbo:
    script: "scripts/api_call_dat_gpt35.py" # Replace with the actual script name if different
    temperature: [0.7, 1.0]
    strategies: ["none", "thesaurus"] # Example LLM-specific parameters
